In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
arrays_divididos = np.split(array , 3)
arrays_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
for i,value in enumerate(arrays_divididos):
    print(f"Parte{i+1} -> {value}")

Parte1 -> [1 2]
Parte2 -> [3 4]
Parte3 -> [5 6]


In [ ]:
#criando array com 1D com temperaturas diarias de um mês (30 dias)
temperaturas = np.array([22,21,23,25,20,19,21,24,26,27,25,22,20,18,19,20,21,22,23,24,25,26,27,28,29,30,29,28,27,26,25,24])
temperaturas

array([22, 21, 23, 25, 20, 19, 21, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [12]:
#dividindo as temperaturas em 4 semanas 
semanas = np.split(temperaturas, 4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [13]:
for i,value in enumerate(semanas):
    print(f"Semanas {i+1} : {value}")

Semanas 1 : [22 21 23 25 20 19 21 24]
Semanas 2 : [26 27 25 22 20 18 19 20]
Semanas 3 : [21 22 23 24 25 26 27 28]
Semanas 4 : [29 30 29 28 27 26 25 24]


In [14]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [20]:
for i,value in enumerate(medias_semanas):
    print(f"Média da Semana {i+1} : {value:.2f}°C")

Média da Semana 1 : 21.88°C
Média da Semana 2 : 22.12°C
Média da Semana 3 : 24.50°C
Média da Semana 4 : 27.25°C
