In [5]:
import numpy as np

In [6]:
array = np.array([10,20,30,40,50])

In [7]:
#Pesqueisar a posição do valor 30
posicao = np.where(array==30)
posicao

(array([2]),)

In [9]:
notas = np.array([50,67,72,48,90,85,60,50])
notas

array([50, 67, 72, 48, 90, 85, 60, 50])

In [10]:
#pesqueisar quais alunos foram aprovados (nota >60)
alunos_aprovado = np.where(notas >60)
alunos_aprovado

(array([1, 2, 4, 5]),)

In [11]:
notas[alunos_aprovado]

array([67, 72, 90, 85])

In [12]:
nota_maxima = np.max(notas)
nota_maxima

np.int64(90)

In [14]:
indice_maximo = np.argmax(notas)
indice_maximo

np.int64(4)