In [1]:
import numpy as np

In [12]:
array_ld = np.array ([1, 2, 3, 4, 5])
print (array_ld.ndim)  # numero de dimensões
print(array_ld.shape,"\n")  # formato do array
print(array_ld)
#array-ld  lista de Dados ,como séries temporis ou coleçao de valores

1
(5,) 

[1 2 3 4 5]


In [6]:

array_2d = np.array ([[1, 2, 3], [4, 5, 6]])
print (array_ld.ndim)  # numero de dimensões
print(array_ld.shape,"\n")  # formato do array
print(array_2d) # matriz 2D, como uma tabela ou imagem

1
(5,) 

[[1 2 3]
 [4 5 6]]


In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim)  # numero de dimensões
print(array_3d.shape,"\n")  # formato do array
print(array_3d) # Imagens em cores (cada matriz representando um canal de cor , como RGB)

3
(2, 2, 2) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)  # numero de dimensões
print(array_4d.shape,"\n")  # formato do array
print(array_4d) # Vídeos (sequências de imagens, onde cada imagem é uma matriz 2D e a sequência é representada por uma dimensão adicional)

4
(2, 3, 4, 5) 

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
