In [1]:
import numpy as np

In [ ]:
array = np.array([[10,20,30],
[40,50,60],
[70,80,90]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
#buscar elemento na linha 1 coluna 2
elemento = array[1,2]
elemento

np.int64(60)

In [30]:
#pegando dados da primeira linha
linha_0 = array[0] 
linha_0

array([10, 20, 30])

In [31]:
#acessar colina 1 
coluna_1 = array[:,1]
coluna_1

array([20, 50, 80])

In [32]:
# fatiando para obter um sub array
subarray = array[0:2,1:3]
subarray

array([[20, 30],
       [50, 60]])

In [35]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [36]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [37]:
#modificando elemento na linha 1 coluna 1
array[1,1]= 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])