In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3,4,5],
[6,7,8,9,10],
[11,12,13,14,15],
[16,17,18,19,20]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#Fatiando as duas primeiras linhas
fatiando_linhas = array[0:2,:]
fatiando_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
#fatiando as 3 primeiras colunas 
fatiando_colunas = array[:,0:3]
fatiando_colunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [9]:
subarray_central = array[1:3,1:3]
subarray_central

array([[ 7,  8],
       [12, 13]])

In [10]:
subarray_lateral = array[2:4,3:5]
subarray_lateral

array([[14, 15],
       [19, 20]])

In [12]:
array[1:3,1:3] = [[90,100], [101 , 102]]
array

array([[  1,   2,   3,   4,   5],
       [  6,  90, 100,   9,  10],
       [ 11, 101, 102,  14,  15],
       [ 16,  17,  18,  19,  20]])