In [1]:
import numpy as np

In [6]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [15]:
soma = np.add(array,10)
soma

array([11, 12, 13, 14, 15])

In [14]:
subtração = np.subtract(array , 5)
subtração

array([-4, -3, -2, -1,  0])

In [13]:
multiplicacao = np.multiply(array,2)
multiplicacao

array([ 2,  4,  6,  8, 10])

In [12]:
divisao = np.divide(array,2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [11]:
#funçoes trigonometricas 
seno = np.sin(array)
seno

cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
#funcoes estatristicas 
media = np.mean(array)
media

np.float64(3.0)

In [23]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [27]:
#comparação
coparacao_maior_que_3 = array > 3
coparacao_maior_que_3

array([False, False, False,  True,  True])

In [28]:
#combinando funções
resultado = np.sqrt(array) + np.power(array,2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [30]:
#funcoes exponenciais
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [31]:
#logaritimo 
logaritimo = np.log(array)
logaritimo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [33]:
#Arredondamento
arredondamento = np.round(array,2)
arredondamento

array([1, 2, 3, 4, 5])

In [34]:
#Potência 
potencia = np.power(array ,3)
potencia

array([  1,   8,  27,  64, 125])