Copy

Uma nova copia do array é criada em memória .Isso significa que as 2 matrizes (original e cópia)são independentes uma da outra 


View


Não é criada uma nova cópia na memória . A view compartilha dados que o array original.

In [1]:
import numpy as np

In [2]:
array_original = np.array ([[1,2,3,],[4,5,6],[7,8,9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#1 Cópia Rasa
array_view = array_original[1:,1:]
array_view

array([[5, 6],
       [8, 9]])

In [4]:
array_view[0,0] = 99
array_view


array([[99,  6],
       [ 8,  9]])

In [5]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [6]:
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [ ]:
array_copia[0,0] = 100
array_copia
array_original

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])