In [4]:
import numpy as np 

In [5]:
#criando dois arrays 
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [ ]:
#Cconcatenando os arrays
novo_array = np.concatenate((array1,array2))
novo_array

array([1, 2, 3, 4, 5, 6])

In [10]:
#Criando arrays para nomes e notas
nomes = np.array(["Alice","Bob","Charlie"])
notas_matematica = np.array([85,90,78])
notas_fisica = np.array([88,76,95])

In [13]:
#Usando np.vstack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes,notas_fisica,notas_matematica))
dados_estudantes

array([['Alice', 'Bob', 'Charlie'],
       ['88', '76', '95'],
       ['85', '90', '78']], dtype='<U21')

In [14]:
#Usando o np.hstack para empilhar horizontalmente 
matriz_notas = np.column_stack((notas_fisica,notas_matematica))
matriz_notas

array([[88, 85],
       [76, 90],
       [95, 78]])

In [21]:
#adiciionando nova coluna com as médias das notas
media_notas = np.mean(matriz_notas , axis =1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final


array([[88. , 85. , 86.5],
       [76. , 90. , 83. ],
       [95. , 78. , 86.5]])